version: '3.8'

services:
  web:
    build: .
    ports:
      - "1337:1337"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=admin
      - MYSQL_PASS=admin
      - MYSQL_DATABASE=db
    command: npm start

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  test:
    build: .
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=admin
      - MYSQL_PASS=admin
      - MYSQL_DATABASE=db
    command: npm test