version: '3.8'

services:
  web:
    build: .
    ports:
      - "1337:1337"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - app-network
    command: npm run start:dev

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    networks:
      - app-network

  test:
    build: .
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command: npm test

networks:
  app-network:
    driver: bridge